version: "3.8"

services:
  tomichan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomichan
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
